forms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crispy/', include('crispy.urls', namespace='crispy')),
    path('htmx/', include('htmx.urls', namespace='htmx')),
]

htmx/urls.py
from django.urls import path
from . import views

app_name = 'cities'

urlpatterns = [
    path('detail/<slug:slug>/', views.detail, name='detail'),
    path('create/<pk>/', views.create_city, name='create-city'),
    path('city_detail/<pk>/', views.detail_city, name='detail-city'),
    path('city_update/<pk>/', views.update_city, name='update-city'),
    path('city_delete/<pk>/', views.delete_city, name='delete-city'),
    path('city-form', views.create_city_form, name='create-city-form'),
    
]

htmx/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

class BaseClass(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        abstract = True
        ordering = ['name']

    def __str__(self):
        return self.name

class Country(BaseClass):
    created = models.DateTimeField(auto_now_add=True)

class City(BaseClass):
    population = models.IntegerField()
    slug = models.SlugField(blank=True, default='')
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(City, self).save()

    def get_absolute_url(self): # < here
        return reverse('cities:detail', args=[str(self.slug)])

htmx/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import City, Country

class CityModelForm(forms.ModelForm):
    class Meta:
        model = City
        fields = ['name', 'population']

CityFormSet = inlineformset_factory(
    Country,
    City,
    CityModelForm,
    can_delete=False,
    min_num=2,
    extra=0
)

htmx/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.db import connection
from django.db.models import Q, Min, Avg, Count
from .models import Country,City
from .forms import CityFormSet, CityModelForm






def detail(request, slug=None): 
    city = get_object_or_404(City, slug=slug)
    return render(request, 'detail.html', {'city': city})

'''def create_city(request, pk):
    country = Country.objects.get(pk=pk)
    formset = CityFormSet(request.POST or None)

    if request.method == 'POST':
        if formset.is_valid():
            formset.instance = country
            formset.save()
            return redirect('cities:create-city', pk=country.id)

    context = {
        'formset' : formset,
        'country' : country
    }

    return render(request, 'create_city.html', context)'''
    
def create_city(request, pk):
    country = Country.objects.get(pk=pk)
    cities = City.objects.filter(country=country)
    form = CityModelForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            city = form.save(commit=False)
            city.country = country
            city.save()
            return redirect('htmx:detail-city', pk=city.id)
        else:
            return render(request, 'htmx/partials/city_form.html', {'form':form})

    context = {
        'form' : form,
        'country' : country,
        'cities' : cities
    }

    return render(request, 'htmx/create_city.html', context)

def create_city_form(request):
    context = {
        'form' : CityModelForm()
    }
    return render(request, 'htmx/partials/city_form.html', context)

def update_city(request, pk):
    city = City.objects.get(pk=pk)
    form = CityModelForm(request.POST or None, instance=city)

    if request.method == 'POST':
        if form.is_valid():
            city = form.save()
            return redirect('htmx:detail-city', pk=city.id)

    context = {
        'form' : form, 
        'city' : city
    }
    return render(request, 'htmx/partials/city_form.html', context)

def detail_city(request, pk):
    city = City.objects.get(pk=pk)
    context = {
        'city' : city
    }
    return render(request, 'htmx/city_detail.html', {'city': city})

def delete_city(request, pk):
    city = City.objects.get(pk=pk)
    city.delete()
    return HttpResponse('')

htmx/templates/htmx/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Htmx Formsets</title>
    <script src="https://unpkg.com/htmx.org@1.5.0"
        integrity="sha384-oGA+prIp5Vchu6we2YkI51UtVzN9Jpx2Z7PnR1I78PnZlN8LkrCT4lqqqmDkyrvI"
        crossorigin="anonymous"></script>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>

<body>
    <div class="py-5 px-4 sm:px-6 max-w-5xl mx-auto">
        {% block content %}
        {% endblock content %}
    </div>

    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
    </script>
</body>

</html>

htmx/templates/htmx/city_detail.html
{% extends 'htmx/base.html' %}

{% block content %}

<div hx-target="this" class="mt-3 py-3 px-3 bg-white shadow border border-gray-100">
    <h3 class="text-lg leading-6 font-medium text-gray-900">
        City Name: {{ city.name }}
    </h3>
    <p class="text-gray-600">Population: {{ city.population }}</p>
    <div class="mt-2">
        <button hx-get="{% url 'htmx:update-city' city.id %}" hx-swap="outerHTML"
            class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Update
        </button>
        <button hx-post="{% url 'htmx:delete-city' city.id %}" hx-swap="outerHTML swap:1s"
            class="ml-2 inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
            Delete
        </button>
    </div>
</div>

{% endblock content %}

htmx/templates/htmx/create_city.html
{% extends 'htmx/base.html' %}

{% block content %}

    <div class="md:flex md:items-center md:justify-between">
        <div class="flex-1 min-w-0">
            <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
                Create city for {{ country.name }}
            </h2>
        </div>
        <div class="mt-4 flex md:mt-0 md:ml-4">
            <button type="button" hx-get="{% url 'htmx:create-city-form' %}" hx-target="#cityforms" hx-swap="beforeend"
                class="ml-3 inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Add form
            </button>
        </div>
    </div>
    
    
    <div id="cityforms" class="py-5 mt-5"></div>
    
    <div class="mt-5 py-5 border-t border-gray-100">
        {% for city in cities %}
            {% include 'city_detail.html' %}
        {% endfor %}
    </div>

{% endblock content %}

htmx/templates/htmx/create_city_test.html
{% extends 'htmx/base.html' %}

{% block content %}
    <h3>Create city for {{ country.name }}</h3>
    <form method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        {{ formset.as_p }}
        <button>Submit</button>
    </form>
{% endblock content %}

htmx/templates/htmx/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>{{ city.name }} | {{ city.population }}</h3>
</body>
</html>